-- Add profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS dateOfBirth DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bloodType VARCHAR(10) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergencyContact VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergencyPhone VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS allergies TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS currentMedications TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;